FROM golang:1.7.5

MAINTAINER 	Viktor Farcic <viktor@farcic.com>

RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates expect netcat && \
    apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D && \
    echo 'deb https://apt.dockerproject.org/repo debian-jessie main' >/etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get install -y docker-engine

RUN go get github.com/docker/docker/api/types && \
    go get github.com/docker/docker/api/types/filters && \
    go get github.com/docker/docker/api/types/swarm && \
    go get github.com/docker/docker/client && \
    go get gopkg.in/robfig/cron.v2 && \
    go get golang.org/x/net/context && \
    go get github.com/gorilla/mux && \
    go get github.com/stretchr/testify/suite